export const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
};

export const COMMUNICATION_STATUS_TYPE = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
  NO_SHOW: 'NO_SHOW',
  RESCHEDULED: 'RESCHEDULED',
};

export const COMMUNICATION_TYPE = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',
  PHONE_CALL: 'PHONE_CALL',
};

export const USER_TYPE = {
  PATIENT: 'USER',
  DOCTOR: 'DOCTOR',
  ADMIN: 'ADMIN',
};

export const SHIFTS = {
  REGULAR: 'REGULAR_SHIFT',
};
